# Generated by Django 4.2 on 2023-04-10 18:53

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date last updated')),
                ('event_status', models.CharField(choices=[('financed', 'Financed'), ('planned', 'Planned'), ('pending', 'Pending'), ('completed', 'Completed')], default='f', max_length=15, verbose_name='Event status')),
                ('attendees', models.IntegerField(verbose_name='Attendees')),
                ('event_date', models.DateField(null=True, verbose_name='Event date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('contract', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contracts.contract', verbose_name='Event')),
                ('support_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, validators=[accounts.validators.validate_support_user], verbose_name='Support contact')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
