# Generated by Django 4.2 on 2023-04-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contracts.contract', verbose_name='Contract'),
        ),
    ]
