# Generated by Django 4.2 on 2023-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('financed', 'Financed'), ('planned', 'Planned'), ('pending', 'Pending'), ('completed', 'Completed')], default='financed', max_length=15, verbose_name='Event status'),
        ),
    ]
