# Generated by Django 4.2 on 2023-05-02 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
        ('events', '0004_eventstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(default=None, limit_choices_to=models.Q(('event', None)), on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['support'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Support contact'),
        ),
    ]
