# Generated by Django 4.2.1 on 2023-05-23 17:34

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_signed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contracts.contract', validators=[events.validators.validate_signed_contract], verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['support'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, validators=[accounts.validators.validate_support_user], verbose_name='Support contact'),
        ),
    ]
