# Generated by Django 4.2 on 2023-04-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date last updated')),
                ('amount', models.FloatField(verbose_name='Price')),
                ('payment_due', models.DateTimeField(verbose_name='Payment due')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
            },
        ),
    ]
