# Generated by Django 4.2.1 on 2023-05-23 16:13

from django.db import migrations, models
from django.apps.registry import Apps


def UpdateSignedContracts(apps: Apps, schema):
    contract_model = apps.get_model("contracts", "Contract")

    contract_model.objects.exclude(event=None).update(signed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Signed'),
        ),
        migrations.RunPython(UpdateSignedContracts, migrations.RunPython.noop),
    ]
