# Generated by Django 4.2 on 2023-04-10 18:53

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('company_name', models.CharField(max_length=250, unique=True, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone line')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Mobile')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date last updated')),
                ('status', models.BooleanField(default=False, verbose_name='Is active client')),
                ('sales_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, validators=[accounts.validators.validate_sales_user], verbose_name='Sales contact')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'get_latest_by': ['date_creation', 'date_updated'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='company_name_idx'),
        ),
    ]
