# Generated by Django 4.2 on 2023-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales'), ('support', 'Support'), ('management', 'Management')], max_length=10, verbose_name='User role'),
        ),
    ]
