# Generated by Django 4.2 on 2023-04-27 15:51

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230411_0115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.LocalUserManager()),
            ],
        ),
    ]
